name: Deploy to prod

# on:
#   workflow_dispatch:
on:
  pull_request:
   types: [opened, synchronize]
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: 🔎 Set GitHub Actions IP to GITHUB_ENV
      run: echo "GITHUB_ACTIONS_IP=$(curl https://api.ipify.org)" >> $GITHUB_ENV
    
    - name: PRINT ECHO GIP
      run: echo "${{ env.GITHUB_ACTIONS_IP }}"

    - name: Setting environment variables..
      run: |
        echo "AWS_DEFAULT_REGION=sa-east-1" >> $GITHUB_ENV
        echo "AWS_SG_NAME=CICD" >> $GITHUB_ENV
        
    - name: Add Github Actions IP to Security group
      run: |
        aws ec2 authorize-security-group-ingress --group-name ${{ env.AWS_SG_NAME }} --protocol all --port all --cidr ${{ env.GITHUB_ACTIONS_IP }}/32    
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}

    - name: WEB HOOK POST REQUEST
      run: |
        curl -X POST http://ec2-18-228-238-80.sa-east-1.compute.amazonaws.com:8080/github-webhook/
          -H "Accept: */*"
          -H content-type: application/json
          -H User-Agent: GitHub-Hookshot/87ca02f
          -H X-GitHub-Delivery: 40223f80-f346-11ed-867f-464ec649efc2
          -H X-GitHub-Event: pull_request
          -H X-GitHub-Hook-ID: 413733004
          -H X-GitHub-Hook-Installation-Target-ID: 638476158
          -H X-GitHub-Hook-Installation-Target-Type: repository
          -d '{
            "action": "synchronize",
            "after": ${{ github.event.after }},
            "before": ${{ github.event.before }},
            "enterprise": ${{ github.event.enterprise }},
            "installation": ${{ github.event.installation }},
            "number": ${{ github.event.number }},
            "organization": ${{ github.event.organization }},
            "pull_request": ${{ github.event.pull_request }},
            "repository": ${{ github.event.repository }},
            "sender": ${{ github.event.sender }},
          }'
              
    - name: Remove Github Actions IP from security group
      run: |
        aws ec2 revoke-security-group-ingress --group-name ${{ env.AWS_SG_NAME }} --protocol tcp --port 22 --cidr ${{ env.GITHUB_ACTIONS_IP }}/32
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
      if: always()