name: Deploy to prod

# on:
#   workflow_dispatch:
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/jenkinsci/jenkinsfile-runner:master

    steps:
    - name: 🔎 Set GitHub Actions IP to GITHUB_ENV
      run: echo "GITHUB_ACTIONS_IP=$(curl https://api.ipify.org)" >> $GITHUB_ENV

    - name: Setting environment variables..
      run: |
        echo "AWS_DEFAULT_REGION=sa-east-1" >> $GITHUB_ENV
        echo "AWS_SG_NAME=CICD" >> $GITHUB_ENV
        
    - name: Add Github Actions IP to Security group
      run: |
        aws ec2 authorize-security-group-ingress --group-name ${{ env.AWS_SG_NAME }} --protocol tcp --port 22 --cidr ${{ env.GITHUB_ACTIONS_IP }}/32    
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
    
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - uses: jenkinsci/jfr-setup-action@master

    - uses:
        jenkinsci/jfr-container-action@master
      with:
        command: run
        jenkinsfile: Jenkinsfile
        pluginstxt: plugins.txt
        jcasc: jcasc.yml

    - name: Deploy to prod server
      uses: appleboy/ssh-action@master
      with:
        host: 18.228.117.134
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~
          git clone git@github.com:paulolopestech/CI-CD.git || cd ~/CI-CD && git pull
              
    - name: Remove Github Actions IP from security group
      run: |
        aws ec2 revoke-security-group-ingress --group-name ${{ env.AWS_SG_NAME }} --protocol tcp --port 22 --cidr ${{ env.GITHUB_ACTIONS_IP }}/32
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
      if: always()