name: get params

on:
  push:
  pull_request:
   types: [opened, synchronize]
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - name : Print Object of PR
      run: echo "The Object of your PR is ${{ github.event.pull_request }}"
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"