name: get params

on:
  push:
  pull_request:
   types: [opened, synchronize]

  info:
    runs-on: ubuntu-20.04
    steps:
    - name : Print Object of PR
      run: echo The Object of your PR is ${{ github.event.pull_request }}